# Generated by Django 5.0.1 on 2024-01-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('student', 'student'), ('teacher', 'teacher')], default='teacher', max_length=7),
            preserve_default=False,
        ),
    ]
